pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
        jdk 'openjdk-11'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Build Project') {
            steps {
                sh 'mvn -DskipTests clean package'
            }
        }
        stage('Run Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Copy Artifacts') {
            steps {
                sh 'sudo ./jenkins/scripts/copyArtifacts.sh'
                set -x
                sh 'NAME=$(mvn help:evaluate -Dexpression=project.name | grep "^[^\[]")'
                set +x
                set -x
                sh 'VERSION=$(mvn help:evaluate -Dexpression=project.version | grep "^[^\[]")'
                set +x
                sh 'sudo cp /target/${NAME}-${VERSION}.jar" "/mnt/zonedisk1/daily_artifacts'
            }
        }
    }
}